#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

max_value = 90

fib_1= 1
fib_2 = 2
total = 0

class fibonacci():
   def __init__(self,fib):
       self.fib = fib

fib_1 = fibonacci(1)
fib_2 = fibonacci(2)

while fibonacci(fib)<=max_value:
    fib_1

test = fibonacci(1,2)

def main():
    pass
if 'main' == 'main':
    main()